name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        with:
          server-ip: ${{ secrets.EC2_PUBLIC_IP }}
          server-port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          local-path: "." # Path to your local files to be deployed
          remote-path: ${{ secrets.REMOTE_PATH }} # Path on remote server to deploy

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo mv /var/www/html /var/www/html_backup # Backup existing content
            sudo mv * /var/www/html # Move new content
